#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Bascule du VPS vers la pile de production du carnet (#69).
#
# CE SCRIPT TOURNE SUR LE VPS, et c'est une contrainte et non une commodité :
# les trois secrets qu'il produit — POSTGRES_PASSWORD, APP_KEY, APP_PASSWORD —
# ne doivent jamais quitter le serveur (docs/deploiement.md). Ils naissent
# ici, par openssl, et n'ont aucune raison de transiter par une autre machine.
#
# Il libère les ports 80 et 443, aujourd'hui tenus par un nginx d'hôte servant
# cinq vhosts dont aucun n'est utilise (#68), puis démarre la pile et vérifie
# la chaîne complète.
#
# Le principe qui gouverne l'ordre : VÉRIFIER AVANT DE COUPER. Tout ce qui
# peut être éprouvé pendant que l'ancien site répond encore l'est d'abord.
# Let's Encrypt ne tolère que cinq échecs par nom et par heure, et la fenêtre
# d'indisponibilité est le pire moment pour découvrir une erreur de frappe.
#
# Il est interruptible : les valeurs déjà écrites dans le .env sont reprises
# à la relance, et les étapes de démontage sont idempotentes.

TOTAL_STAGES=8

PILE_DIR="${PILE_DIR:-/opt/homecomparator}"
ENV_FILE="$PILE_DIR/.env"

banner "Bascule du VPS : le carnet en HTTPS"

# -- 1 ---------------------------------------------------------------------
stage "Vérifier la machine et les fichiers"
if [[ "$(id -u)" -ne 0 ]]; then
  warn "Ce script doit tourner en root : il arrête des services système."
  exit 1
fi
say "Trois fichiers doivent avoir été déposés sur cette machine :"
note "  docker-compose.prod.yml, Caddyfile, et ce script."
say ""
mkdir -p "$PILE_DIR"
manque=0
for f in docker-compose.prod.yml Caddyfile; do
  if [[ -f "$PILE_DIR/$f" ]]; then
    say "  [ok] $PILE_DIR/$f"
  elif [[ -f "/root/$f" ]]; then
    cp "/root/$f" "$PILE_DIR/$f"
    say "  [ok] $f — repris depuis /root et copié dans $PILE_DIR"
  else
    warn "  [manquant] $f (ni dans $PILE_DIR, ni dans /root)"
    manque=1
  fi
done
if [[ "$manque" -eq 1 ]]; then
  say ""
  note "Depuis la machine de développement, à la racine du dépôt :"
  note "  scp docker-compose.prod.yml Caddyfile scripts/basculer-vps.sh root@srv571823:/root/"
  exit 1
fi
say ""
# Docker doit répondre avant tout le reste : ce script arrête des services
# et démarre une pile. Découvrir qu'il ne répond pas après avoir coupé les
# ports laisserait la machine sans rien qui serve.
if ! command -v docker >/dev/null 2>&1; then
  warn "La commande « docker » est introuvable sur cette machine."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  warn "« docker » existe mais le démon ne répond pas :"
  docker info 2>&1 | tail -n 5 | sed 's/^/      /'
  exit 1
fi
note "Docker  : $(docker --version 2>/dev/null || echo ABSENT)"
note "Compose : $(docker compose version --short 2>/dev/null || echo ABSENT)"
pause "Continuer ?"

# -- 2 ---------------------------------------------------------------------
stage "Le nom de domaine, et son DNS"
say "Caddy demandera un certificat pour ce nom. Il doit DÉJÀ pointer vers"
say "cette machine : la validation ACME le joint sur le port 80."
ask DOMAINE "Nom de domaine (ex. home-comparator.puzzlemind.fr) :"
if [[ -z "$DOMAINE" ]]; then
  warn "Le nom de domaine est obligatoire."
  exit 1
fi
say ""
ip_publique=$(curl -fsS --max-time 10 https://api.ipify.org 2>/dev/null || echo "")
ip_domaine=$(getent hosts "$DOMAINE" 2>/dev/null | awk '{print $1}' | head -n1)
note "Cette machine : ${ip_publique:-inconnue}"
note "$DOMAINE : ${ip_domaine:-NE RÉSOUT PAS}"
say ""
if [[ -z "$ip_domaine" ]]; then
  warn "Le nom ne résout pas. La validation ACME échouerait à coup sûr."
  note "Créez l'enregistrement A chez l'hébergeur DNS, attendez la"
  note "propagation, puis relancez ce script."
  exit 1
elif [[ -n "$ip_publique" && "$ip_domaine" != "$ip_publique" ]]; then
  warn "Le nom résout vers une AUTRE adresse que celle de cette machine."
  note "La validation ACME échouerait, et chaque échec compte dans le"
  note "plafond de cinq par nom et par heure."
  confirm "Continuer malgré tout ?" || exit 1
else
  say "Le DNS pointe bien ici."
fi
write_env DOMAINE "$DOMAINE"
say ""
step "Let's Encrypt prévient à cette adresse avant qu'un certificat n'expire"
note "sans avoir été renouvelé. C'est le seul avertissement avant la panne."
ask COURRIEL_ACME "Adresse de contact ACME :"
write_env COURRIEL_ACME "$COURRIEL_ACME"
pause "Continuer ?"

# -- 3 ---------------------------------------------------------------------
stage "Les images à déployer"
say "Les images ont été publiées depuis la machine de développement"
say "(scripts/publier-images.sh). Reprenez les deux valeurs affichées."
ask GHCR_COMPTE "Compte GitHub portant les images :"
GHCR_COMPTE=$(printf '%s' "$GHCR_COMPTE" | tr '[:upper:]' '[:lower:]')
ask VERSION "Version à déployer (ex. 0.1.0) :"
if [[ -z "$GHCR_COMPTE" || -z "$VERSION" ]]; then
  warn "Compte et version sont obligatoires : sans eux la pile ne démarre pas."
  exit 1
fi
write_env GHCR_COMPTE "$GHCR_COMPTE"
write_env VERSION "$VERSION"
pause "Continuer vers les secrets ?"

# -- 4 ---------------------------------------------------------------------
stage "Les secrets, générés ici et nulle part ailleurs"
say "Ces trois valeurs ne quittent jamais ce serveur. Elles ne sont recopiées"
say "ni dans le dépôt, ni dans les secrets GitHub : rien d'autre ne les lit."
say ""
if grep -qE '^POSTGRES_PASSWORD=.+' "$ENV_FILE" 2>/dev/null; then
  say "Un mot de passe de base existe déjà dans le .env."
  note "Le régénérer rendrait la base existante inaccessible."
  if confirm "En générer un NOUVEAU malgré tout ?"; then
    write_env POSTGRES_PASSWORD "$(openssl rand -base64 24)"
  else
    say "Conservé."
  fi
else
  write_env POSTGRES_PASSWORD "$(openssl rand -base64 24)"
  say "Mot de passe de la base : généré."
fi
if grep -qE '^APP_KEY=.+' "$ENV_FILE" 2>/dev/null; then
  say "Une APP_KEY existe déjà : conservée (la changer invalide ce qu'elle chiffre)."
else
  write_env APP_KEY "$(openssl rand -base64 24)"
  say "APP_KEY : générée."
fi
write_env POSTGRES_USER "homecomparator"
write_env POSTGRES_DB "homecomparator"
write_env LOG_LEVEL "info"
say ""
step "APP_PASSWORD est le seul qui se choisit : c'est le mot de passe unique"
note "qui protège l'accès au carnet, et qui se tape à chaque connexion."
note "Le changer plus tard ne déconnecte pas les sessions ouvertes."
ask_secret APP_PASSWORD "Mot de passe d'accès au carnet :"
if [[ -z "$APP_PASSWORD" ]]; then
  warn "Sans mot de passe, l'API refuse de démarrer — et c'est voulu."
  exit 1
fi
write_env APP_PASSWORD "$APP_PASSWORD"
chmod 600 "$ENV_FILE"
say ""
say "Fichier d'environnement écrit, lisible par root seul."
pause "Continuer vers les vérifications ?"

# -- 5 ---------------------------------------------------------------------
stage "Tout vérifier pendant que l'ancien site répond encore"
say "Rien de cette étape n'interrompt quoi que ce soit."
say ""
cd "$PILE_DIR"
step "La configuration Compose est-elle complète ?"
if docker compose -f docker-compose.prod.yml config -q 2>/tmp/compose-err; then
  say "  [ok] configuration lisible"
else
  warn "  [échec] configuration refusée :"
  sed 's/^/      /' /tmp/compose-err
  exit 1
fi
step "Le Caddyfile est-il valide ?"
note "Compose ne regarde pas les fichiers montés : sans ce contrôle, un"
note "Caddyfile absent ne se découvrirait qu'après la coupure des ports."
if docker run --rm --env-file "$ENV_FILE" \
     -v "$PILE_DIR/Caddyfile:/etc/caddy/Caddyfile:ro" \
     caddy:2-alpine caddy validate --config /etc/caddy/Caddyfile >/tmp/caddy-err 2>&1; then
  say "  [ok] Caddyfile valide"
else
  warn "  [échec] Caddyfile refusé :"
  tail -n 5 /tmp/caddy-err | sed 's/^/      /'
  exit 1
fi
say ""
step "Tirer les images maintenant : c'est long, et l'ancien site répond encore."
note "Un jeton GitHub est nécessaire (read:packages), les images étant privées."
note "Il n'est pas écrit sur le disque : la session est refermée aussitôt après."
note "Sur cette machine, `gh` n'est en principe pas installé : le jeton se"
note "colle donc à la main. Attention au retour chariot invisible du collage,"
note "que ce script retire de lui-même."
ask_secret GH_JETON "Jeton GitHub (affichage vide) :"
# Espaces et retour chariot parasites du collage : invisibles, ils font rendre
# au registre un « denied » qui accuse le jeton plutôt que la saisie.
GH_JETON=$(printf '%s' "$GH_JETON" | tr -d '\r\n[:space:]')
if [[ -z "$GH_JETON" ]]; then
  warn "  [échec] aucun jeton reçu : le collage n'a pas abouti."
  exit 1
fi
say "  Jeton reçu : ${#GH_JETON} caractères."
# Sortie non masquée : ce que dit le registre est la seule chose utile quand
# la connexion échoue, et la capturer dans un fichier l'a déjà fait perdre.
if printf '%s' "$GH_JETON" | docker login ghcr.io -u "$GHCR_COMPTE" --password-stdin; then
  say "  [ok] session ouverte vers ghcr.io"
else
  warn "  [échec] connexion refusée : la raison est écrite juste au-dessus."
  note "  Le jeton doit porter read:packages, et le compte être $GHCR_COMPTE."
  exit 1
fi
if docker compose -f docker-compose.prod.yml pull; then
  say "  [ok] images présentes sur la machine"
else
  warn "  [échec] le tirage a échoué : vérifiez le compte, la version, la visibilité"
  docker logout ghcr.io >/dev/null 2>&1 || true
  exit 1
fi
docker logout ghcr.io >/dev/null 2>&1 || true
say "  [ok] session vers le registre refermée"
say ""
say "Tout est prêt. La bascule proprement dite n'a plus rien à découvrir."
pause "Continuer ?"

# -- 6 ---------------------------------------------------------------------
stage "Libérer les ports 80 et 443"
warn "C'EST L'ÉTAPE IRRÉVERSIBLE. À partir d'ici, le VPS ne sert plus rien"
warn "jusqu'à ce que la pile démarre et obtienne son certificat."
say ""
say "Vont être arrêtés — aucun n'est utilisé (#68) :"
note "  - la pile Compose cooking-prod (volumes CONSERVÉS)"
note "  - nginx de l'hôte, et sa réactivation au démarrage"
note "  - certbot et son timer : les certificats passent à Caddy"
note "  - PM2 et son application fantôme"
say ""
confirm "Libérer les ports maintenant ?" || { say "Interrompu. Rien n'a été touché."; exit 0; }
say ""
for d in /root/cooking-prod /opt/cooking-prod /srv/cooking-prod; do
  if [[ -d "$d" ]]; then
    step "Arrêt de $d (sans -v : les volumes restent)…"
    (cd "$d" && docker compose down) || warn "échec, à vérifier à la main"
    break
  fi
done
step "Arrêt et désactivation de nginx…"
systemctl stop nginx 2>/dev/null || true
systemctl disable nginx 2>/dev/null || true
step "Arrêt et désactivation de certbot…"
systemctl stop certbot.timer 2>/dev/null || true
systemctl disable certbot.timer 2>/dev/null || true
systemctl stop certbot.service 2>/dev/null || true
systemctl disable certbot.service 2>/dev/null || true
step "Retrait de PM2…"
pm2 delete all >/dev/null 2>&1 || true
pm2 unstartup >/dev/null 2>&1 || true
pm2 kill >/dev/null 2>&1 || true
say ""
step "La tâche cron de sauvegarde de l'ancienne base :"
note "elle échouerait chaque nuit en silence si on la laissait."
crontab -l 2>/dev/null | sed 's/^/      /' || note "      (aucune tâche cron)"
note "Retirez la ligne concernée à la main après ce script : crontab -e"
say ""
step "Plus rien ne doit tenir 80 ni 443 :"
restants=$(ss -lntp 2>/dev/null | grep -E ':(80|443)[[:space:]]' || true)
if [[ -n "$restants" ]]; then
  warn "Des processus tiennent encore les ports :"
  printf '%s\n' "$restants" | sed 's/^/      /'
  confirm "Continuer malgré tout ? (Caddy ne pourra pas se lier)" || exit 1
else
  say "  [ok] les deux ports sont libres"
fi
say ""
step "Aucun second mécanisme de certificats ne doit subsister :"
doubles=$( { systemctl list-timers --all 2>/dev/null | grep -iE 'certbot|acme' || true; for c in /etc/cron.d/*certbot* /etc/cron.d/*letsencrypt*; do [[ -e "$c" ]] && printf '%s\n' "$c"; done; } )
if [[ -n "$doubles" ]]; then
  warn "Restes possibles, à examiner après la bascule :"
  printf '%s\n' "$doubles" | sed 's/^/      /'
else
  say "  [ok] aucun mécanisme concurrent"
fi
pause "Démarrer la pile ?"

# -- 7 ---------------------------------------------------------------------
stage "Démarrer, et obtenir le certificat"
cd "$PILE_DIR"
if ! docker compose -f docker-compose.prod.yml up -d; then
  warn "Le démarrage a échoué."
  note "Journaux : docker compose -f docker-compose.prod.yml logs"
  exit 1
fi
say ""
say "Pile démarrée. Caddy demande maintenant son certificat à Let's Encrypt."
note "Cela prend de quelques secondes à une minute."
say ""
obtenu=0
for _ in $(seq 1 30); do
  if docker compose -f docker-compose.prod.yml logs caddy 2>/dev/null | grep -q "certificate obtained successfully"; then
    obtenu=1; break
  fi
  if docker compose -f docker-compose.prod.yml logs caddy 2>/dev/null | grep -qiE "could not get certificate|too many|rateLimited"; then
    break
  fi
  sleep 4
done
if [[ "$obtenu" -eq 1 ]]; then
  say "  [ok] certificat obtenu"
else
  warn "Le certificat n'est pas confirmé. Lisez les journaux AVANT de relancer :"
  note "  docker compose -f docker-compose.prod.yml logs caddy | tail -40"
  warn "Chaque tentative ratée compte dans les cinq par nom et par heure."
  docker compose -f docker-compose.prod.yml logs caddy 2>/dev/null | tail -n 12 | sed 's/^/      /'
fi
pause "Passer aux vérifications ?"

# -- 8 ---------------------------------------------------------------------
stage "Vérifier la chaîne complète"
say "Trois vérifications, qui sont les trois derniers critères de #69."
say ""
step "La redirection du clair vers le chiffré :"
code=$(curl -sS -o /dev/null -w '%{http_code}' "http://$DOMAINE/" --max-time 15 2>/dev/null || echo "--")
if [[ "$code" == "308" || "$code" == "301" || "$code" == "302" ]]; then
  say "  [ok] HTTP répond $code (redirection)"
else
  warn "  [échec] HTTP a répondu $code"
fi
say ""
step "Le certificat et la route de santé :"
sante=$(curl -sS "https://$DOMAINE/api/health" --max-time 15 2>&1 || echo "ÉCHEC")
if printf '%s' "$sante" | grep -q '"status"'; then
  say "  [ok] $sante"
  note "    (certificat accepté sans -k : la chaîne de confiance est valide)"
else
  warn "  [échec] $sante"
fi
say ""
step "La connexion par mot de passe unique :"
code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 -X POST "https://$DOMAINE/api/auth/session" -H 'Content-Type: application/json' -d "{\"motDePasse\":\"$APP_PASSWORD\"}" 2>/dev/null || echo "--")
if [[ "$code" == "200" ]]; then
  say "  [ok] connexion acceptée"
else
  warn "  [échec] la connexion a répondu $code"
fi
say ""
warn "Reste à vérifier à la main, dans un navigateur :"
note "  l'envoi d'une Photo, plafond de taille compris. Une photo de quelques"
note "  Mo doit passer, et une série aussi. Un refus doit venir de l'API en"
note "  nommant le fichier en cause, et non d'un proxy sur une réponse muette."
say ""
pause "Terminer ?"

finish
printf '  %sLe carnet répond sur%s https://%s\n\n' "$BOLD" "$RESET" "$DOMAINE"
note "Journaux           : cd $PILE_DIR && docker compose -f docker-compose.prod.yml logs -f"
note "Redémarrer         : docker compose -f docker-compose.prod.yml restart"
note "Changer de version : modifier VERSION dans $ENV_FILE, puis pull + up -d"
printf '\n'
note "Volumes de l'ancienne pile : CONSERVÉS. À supprimer plus tard, à froid."
note "Il reste à retirer la ligne de cron de l'ancienne sauvegarde (crontab -e)."
printf '\n'
