#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Préparation du déploiement automatique (#70, ADR-0018).
#
# Ce wizard pose ce dont les workflows ont besoin pour tourner :
#   - un utilisateur `deploy` non privilégié sur le VPS, et sa clé ;
#   - les cinq secrets GitHub que `deployer.yml` lit ;
#   - le dossier de la pile, s'il n'existe pas encore.
#
# Il tourne sur une MACHINE DE DÉVELOPPEMENT. La clé privée n'est écrite
# qu'ici, le temps de la poser dans les secrets GitHub, puis effacée : elle
# vit ensuite dans les secrets et, pour sa moitié publique, sur le VPS.
#
# Il est relançable : il remplace la clé au lieu d'en empiler une seconde,
# et ne touche jamais au `.env` du serveur.

TOTAL_STAGES=6

# Rien à persister localement : tout va dans les secrets GitHub ou sur le VPS.
ENV_FILE="/dev/null"

banner "Préparer le déploiement automatique"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Vérifier les outils"
say "Ce wizard a besoin de « gh » authentifié et d'un accès SSH au VPS."
if [[ ! -f .github/workflows/deployer.yml ]]; then
  warn "Le workflow de déploiement est introuvable depuis ici."
  note "Lancez ce script depuis la racine du dépôt :"
  note "  bash scripts/preparer-deploiement.sh"
  exit 1
fi
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI est absent ou non authentifié."
  note "Sans lui, les secrets ne peuvent pas être posés."
  note "Installez-le, puis : gh auth login"
  exit 1
fi
say "  [ok] gh authentifié"
if ! command -v ssh-keygen >/dev/null 2>&1; then
  warn "ssh-keygen est introuvable : impossible de générer la clé."
  exit 1
fi
say "  [ok] ssh-keygen présent"
pause "Prêt à continuer ?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Le serveur et le domaine"
say "Ces valeurs deviendront des secrets GitHub, lus par le workflow."
ask VPS_HOTE "Hôte du VPS (nom ou IP, ex. srv571823) :"
ask VPS_DOMAINE "Nom de domaine du carnet (ex. home-comparator.puzzlemind.fr) :"
if [[ -z "$VPS_HOTE" || -z "$VPS_DOMAINE" ]]; then
  warn "Les deux valeurs sont obligatoires."
  exit 1
fi
say ""
step "Sous quel compte administrez-vous le VPS aujourd'hui ?"
note "C'est par lui que l'utilisateur de déploiement sera créé."
note "Ce n'est PAS le compte que le workflow utilisera ensuite."
ask ADMIN_UTILISATEUR "Compte d'administration (ex. root) :"
ADMIN_UTILISATEUR="${ADMIN_UTILISATEUR:-root}"

# Le dossier de la pile sur le serveur. `deployer.yml` porte la même valeur
# dans son propre `DOSSIER` : les deux doivent bouger ensemble.
DOSSIER_DISTANT=/opt/homecomparator

# ── 3 ─────────────────────────────────────────────────────────────────────
# **Cette étape précède toute connexion, et l'ordre est le fond du sujet.**
# Le raisonnement qui la justifie — on ne vérifie rien en demandant sa clé à
# la machine à laquelle on s'apprête à faire confiance — condamne tout autant
# de lui parler d'abord et de la vérifier ensuite. Une empreinte confirmée
# après que l'utilisateur `deploy` a été créé, la clé publique installée et un
# mot de passe d'administration présenté ne protège plus rien : tout a déjà
# été dit à l'interlocuteur, quel qu'il soit (#86).
stage "Relever et confirmer l'empreinte du serveur"
say "Avant de parler au serveur, il faut savoir que c'est bien lui."
note "Le workflow refuse de se connecter à un hôte qu'il ne reconnaît pas."
note "L'empreinte est posée depuis un secret, et non récoltée à la volée par"
note "le workflow : demander sa clé à la machine à laquelle on s'apprête à"
note "faire confiance ne vérifie rien — un intermédiaire serait cru sur parole."
say ""
# La sortie d'erreur sert ici aussi (#100) : `ssh-keyscan` distingue un nom
# qui ne résout pas d'un port qui ne répond pas, et les deux se corrigent
# ailleurs — l'un dans la saisie de l'étape précédente, l'autre sur le
# serveur ou son pare-feu.
erreur_scan=$(mktemp)
EMPREINTE=$(ssh-keyscan -t ed25519 "$VPS_HOTE" 2>"$erreur_scan")
if [[ -z "$EMPREINTE" ]]; then
  warn "Impossible de relever l'empreinte de $VPS_HOTE."
  if [[ -s "$erreur_scan" ]]; then
    warn "Ce que ssh-keyscan a répondu :"
    while IFS= read -r ligne; do warn "  $ligne"; done < "$erreur_scan"
  fi
  note "Vérifiez le nom d'hôte, et que le port 22 répond."
  rm -f "$erreur_scan"
  exit 1
fi
rm -f "$erreur_scan"
say "Empreinte relevée :"
note "  $(printf '%s' "$EMPREINTE" | ssh-keygen -lf - 2>/dev/null || echo '?')"
say ""
warn "Comparez-la à celle lue sur la CONSOLE du serveur, chez l'hébergeur."
note "C'est le seul moment où la comparaison a un sens : elle vient d'être"
note "relevée par le réseau, donc par le canal même dont elle doit protéger."
note "Sur le VPS : ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub"
if ! confirm "L'empreinte correspond-elle ?"; then
  warn "Arrêt : l'empreinte n'a pas été confirmée."
  note "Rien n'a été créé sur le serveur, et aucun secret n'a été posé."
  exit 1
fi
say ""
# L'empreinte confirmée est **opposée** aux connexions qui suivent, et non
# simplement gardée pour le secret : sans cela le wizard vérifierait une
# empreinte pour n'en exiger aucune, et `known_hosts` de la machine de
# développement — qui peut déjà porter une entrée pour cet hôte, jamais
# vérifiée — trancherait à sa place. Le fichier est temporaire : il ne vaut
# que pour cette exécution, et ne modifie pas le `known_hosts` de l'opérateur.
HOTES_CONNUS=$(mktemp)
printf '%s\n' "$EMPREINTE" > "$HOTES_CONNUS"
# `trap` plutôt qu'un `rm` en fin de script : les sorties d'erreur sont
# nombreuses ici, et chacune devrait sinon penser à nettoyer.
trap 'rm -f "$HOTES_CONNUS"' EXIT
say "  [ok] empreinte confirmée, opposée aux connexions de ce wizard"
say ""
say "Vérification de l'accès…"
# **La sortie d'erreur de `ssh` est retenue, pas jetée (#100).** Les causes
# d'échec appellent des gestes opposés — poser une clé, corriger un nom,
# ouvrir un port, ou **s'arrêter** parce que l'hôte n'est pas celui qu'on
# croit — et `ssh` vient précisément de dire laquelle. La jeter renvoyait
# l'opérateur relancer à la main pour découvrir ce que le script savait
# déjà.
if ! erreur_ssh=$(ssh -o BatchMode=yes -o ConnectTimeout=10 \
     -o UserKnownHostsFile="$HOTES_CONNUS" -o StrictHostKeyChecking=yes \
     "$ADMIN_UTILISATEUR@$VPS_HOTE" true 2>&1); then
  warn "Connexion SSH impossible sans interaction."
  if [ -n "$erreur_ssh" ]; then
    warn "Ce que ssh a répondu :"
    while IFS= read -r ligne; do warn "  $ligne"; done <<< "$erreur_ssh"
  fi

  # **`Host key verification failed` est la seule des causes où relancer est
  # le mauvais conseil.** Les autres se corrigent et se réessaient ; celle-ci
  # dit que la machine au bout du fil ne présente pas la clé attendue, et
  # insister reviendrait à passer outre l'avertissement.
  if printf '%s' "$erreur_ssh" | grep -qi "host key verification failed"; then
    warn ""
    warn "L'empreinte présentée ne correspond pas à celle confirmée à l'étape 2."
    warn "Ne relancez pas : la machine au bout du fil n'est peut-être pas la"
    warn "vôtre. Vérifiez l'empreinte sur la console de l'hébergeur avant tout."
  else
    note "Vérifiez que « ssh $ADMIN_UTILISATEUR@$VPS_HOTE » aboutit sans mot de passe."
    note "Si cette commande réussit dans votre terminal alors qu'elle échoue"
    note "ici, deux « ssh » coexistent peut-être sur la machine et ne voient"
    note "pas le même agent de clés (#102)."
  fi
  exit 1
fi
say "  [ok] $ADMIN_UTILISATEUR@$VPS_HOTE répond"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Créer l'utilisateur de déploiement"
say "Le workflow se connectera sous « deploy », et non sous root."
note "Un secret de CI vaut l'accès qu'il ouvre (#76) : celui-ci n'ouvrira que"
note "ce qu'un déploiement fait réellement."
say ""
warn "L'appartenance au groupe « docker » équivaut en pratique à root sur l'hôte :"
note "un conteneur privilégié monte le système de fichiers de la machine."
note "C'est assumé — le déploiement pilote Docker, il lui faut le socket —"
note "mais « non privilégié » désigne donc ici l'absence de sudo et de session"
note "root, et non une impossibilité d'escalade."
say ""
confirm "Créer l'utilisateur « deploy » sur $VPS_HOTE ?" || exit 1
# La sortie du script distant est **relayée et retenue** : l'absence de `.env`
# qu'il constate doit survivre au `_clear` des étapes suivantes, sans quoi le
# seul avertissement disparaît quatre écrans avant le verdict final.
SORTIE_DISTANTE=$(ssh -o UserKnownHostsFile="$HOTES_CONNUS" \
  -o StrictHostKeyChecking=yes "$ADMIN_UTILISATEUR@$VPS_HOTE" bash -s <<'DISTANT'
set -euo pipefail
if id deploy >/dev/null 2>&1; then
  echo "  [ok] l'utilisateur deploy existe déjà"
else
  useradd --create-home --shell /bin/bash deploy
  echo "  [ok] utilisateur deploy créé"
fi
usermod -aG docker deploy
echo "  [ok] deploy est membre du groupe docker"
mkdir -p /opt/homecomparator
# **Sans `-R`, et c'est délibéré.** La cible réelle est le dossier ; un `-R`
# traverserait par effet de bord le `.env` posé lors de #69, qui porte les
# trois secrets ne quittant jamais la machine, et demain les sauvegardes de
# #71. Un changement de propriétaire sur un fichier de secrets se décide, il
# ne s'attrape pas en passant (#86).
chown deploy:deploy /opt/homecomparator
echo "  [ok] /opt/homecomparator appartient à deploy"
# Le .env n'est PAS créé ni modifié : il porte les trois secrets qui ne
# quittent jamais la machine, et rien ici ne doit pouvoir les écraser.
if [ -f /opt/homecomparator/.env ]; then
  # **Le propriétaire est posé avant le mode, et les deux vont ensemble.**
  # Le `chown` du dossier ci-dessus ne descend volontairement pas jusqu'ici,
  # mais `600` sans propriétaire `deploy` rendrait le fichier illisible par
  # le compte qui lance la pile — `docker compose` échouerait sur le garde
  # `POSTGRES_PASSWORD:?`, et la cause serait à trois écrans de l'effet.
  # C'est bien un changement délibéré sur ce fichier, et non un effet de
  # bord de `-R` : `deploy` doit le lire, lui seul, et personne d'autre.
  chown deploy:deploy /opt/homecomparator/.env
  chmod 600 /opt/homecomparator/.env
  echo "  [ok] .env existant conservé, lisible par deploy seul"
else
  echo "  [!] aucun .env dans /opt/homecomparator"
  echo "      à renseigner avant le premier déploiement (docs/deploiement.md)"
  # Marqueur lu par le wizard, qui refusera d'annoncer « prêt ».
  echo "SANS_ENV"
fi
DISTANT
)
# Tout sauf le marqueur, qui n'a pas à s'afficher.
printf '%s\n' "$SORTIE_DISTANTE" | grep -v '^SANS_ENV$' || true
if printf '%s' "$SORTIE_DISTANTE" | grep -q '^SANS_ENV$'; then
  ENV_MANQUANT=1
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Générer la clé de déploiement"
say "Une clé DÉDIÉE, qui se révoque sans casser votre propre accès."
# **Un dossier réservé, et non un nom libre.** `mktemp -u` rendait un nom en
# supprimant le fichier qui le réservait, laissant un nom prévisible et
# occupable entre ce retour et l'écriture par `ssh-keygen`. Sur une machine
# de développement où `/tmp` est partagé, cela ouvrait un déni de service par
# occupation du nom — `ssh-keygen` refusant d'écraser. Le dossier, lui, est
# réservé par `mktemp` et porte 700 avant que rien n'y soit écrit (#86).
CLE_DOSSIER=$(mktemp -d)
chmod 700 "$CLE_DOSSIER"
CLE_TEMP="$CLE_DOSSIER/id_deploiement"
# Le nettoyage rejoint celui de l'empreinte, posé à l'étape 3. Les sorties
# d'erreur qui suivent n'ont donc plus à effacer la clé elles-mêmes ; celle
# du verdict final, qui la CONSERVE délibérément quand un secret a échoué,
# est traitée à part.
trap 'rm -f "$HOTES_CONNUS"; rm -rf "$CLE_DOSSIER"' EXIT
# Ed25519 : clé courte et sans le choix de taille que RSA impose. Sans
# passphrase, le workflow n'ayant personne pour la saisir.
ssh-keygen -t ed25519 -N '' -C "github-actions-homecomparator-deploy" \
  -f "$CLE_TEMP" >/dev/null
say "  [ok] clé générée (ed25519, sans passphrase)"
say ""
step "Installation de la moitié publique sur le VPS…"
# La clé publique voyage par l'entrée standard plutôt qu'interpolée dans le
# script distant : elle contient des espaces et un commentaire, et une
# interpolation la ferait recouper par le shell du serveur.
{
  cat "$CLE_TEMP.pub"
  cat <<'DISTANT'
set -euo pipefail
install -d -m 700 -o deploy -g deploy /home/deploy/.ssh
touch /home/deploy/.ssh/authorized_keys
# La ligne est retirée avant d'être ajoutée : relancer ce wizard remplace la
# clé au lieu d'en empiler une seconde.
grep -v 'github-actions-homecomparator-deploy' \
  /home/deploy/.ssh/authorized_keys > /home/deploy/.ssh/nouveau || true
# `restrict` coupe redirection de ports, agent, X11 et TTY. Le déploiement
# n'a besoin d'aucun des quatre, et les retirer réduit ce que la clé ouvre
# si elle fuit (#76). `pty` est rendu ensuite : `ssh` en a besoin pour la
# commande distante.
printf 'restrict,pty %s\n' "$cle" >> /home/deploy/.ssh/nouveau
mv /home/deploy/.ssh/nouveau /home/deploy/.ssh/authorized_keys
chmod 600 /home/deploy/.ssh/authorized_keys
chown -R deploy:deploy /home/deploy/.ssh
echo "  [ok] clé publique installée pour deploy"
DISTANT
} | ssh -o UserKnownHostsFile="$HOTES_CONNUS" -o StrictHostKeyChecking=yes \
      "$ADMIN_UTILISATEUR@$VPS_HOTE" \
      "read -r cle; export cle; bash -s"
say ""
step "Vérification : la clé fait-elle ce que le déploiement lui demandera ?"
# **L'empreinte confirmée sert ici aussi.** Cette vérification passait
# `StrictHostKeyChecking=no` sur `/dev/null` : elle acceptait donc n'importe
# quel hôte, au moment précis où elle prétend éprouver la clé de déploiement.
# Le workflow, lui, opposera l'empreinte du secret — la vérification et ce
# qu'elle vérifie doivent se faire dans les mêmes conditions (#86).
#
# **La sortie d'erreur est retenue (#100)**, et le « ou » du message
# d'échec disait bien l'ambiguïté qu'elle lève : une clé refusée
# (`Permission denied`) et un `deploy` hors du groupe `docker`
# (`permission denied while trying to connect to the Docker daemon`) sont
# deux pannes distinctes, qui se corrigent différemment.
erreur_cle=$(ssh -i "$CLE_TEMP" -o BatchMode=yes -o ConnectTimeout=10 \
     -o UserKnownHostsFile="$HOTES_CONNUS" -o StrictHostKeyChecking=yes \
     "deploy@$VPS_HOTE" 'docker ps >/dev/null && echo ok' 2>&1)

if printf '%s' "$erreur_cle" | grep -q ok; then
  say "  [ok] deploy@$VPS_HOTE répond et joint Docker"
else
  warn "La clé ne fonctionne pas, ou deploy ne joint pas le socket Docker."
  if [ -n "$erreur_cle" ]; then
    warn "Ce que ssh a répondu :"
    while IFS= read -r ligne; do warn "  $ligne"; done <<< "$erreur_cle"
  fi
  if printf '%s' "$erreur_cle" | grep -qi "docker daemon\|docker.sock"; then
    warn "La clé ouvre bien la session : c'est l'accès à Docker qui manque."
    warn "« usermod -aG docker deploy » puis une nouvelle session le corrige."
  fi
  exit 1
fi

# **Le dépôt d'un fichier est éprouvé à part, et cette seconde vérification
# n'est pas un doublon de la première (#106).** Ouvrir une session et y
# déposer un fichier sont deux capacités distinctes, qu'`authorized_keys`
# accorde séparément : `restrict` ci-dessus laisse passer la commande
# distante tout en coupant le sous-système SFTP.
#
# Ne mesurer que la session déclarait donc bonne une clé avec laquelle le
# déploiement échouait à sa toute première étape — et l'échec se découvrait
# en production, après la pose du tag, au prix d'un numéro de version
# (#104, #105).
#
# La vérification emprunte exactement le chemin du workflow — `ssh` et
# l'entrée standard, mêmes options — car une vérification qui s'y prendrait
# autrement éprouverait autre chose que ce qu'on déploie.
step "Vérification : la clé peut-elle déposer un fichier dans $DOSSIER_DISTANT ?"
# **La sortie d'erreur de `ssh` est conservée et rendue telle quelle.** La
# jeter dans le contrôle même qui sert à diagnostiquer cette panne
# retirerait la seule phrase qui nomme la cause — « Permission denied »,
# « Connection refused », « Host key verification failed » désignent trois
# incidents distincts que rien d'autre ne distingue ensuite. C'est ce qui a
# rendu #104 long à établir, et #100 le reproche déjà ailleurs dans ce
# script.
TEMOIN="essai-wizard-$$"
ERREUR_SSH=$(mktemp)
if printf 'essai\n' | ssh -T -i "$CLE_TEMP" -o BatchMode=yes -o ConnectTimeout=10 \
     -o UserKnownHostsFile="$HOTES_CONNUS" -o StrictHostKeyChecking=yes \
     "deploy@$VPS_HOTE" "cat > '$DOSSIER_DISTANT/$TEMOIN' && rm -f '$DOSSIER_DISTANT/$TEMOIN'" \
     2>"$ERREUR_SSH"; then
  say "  [ok] la clé dépose un fichier dans $DOSSIER_DISTANT"
  rm -f "$ERREUR_SSH"
else
  warn "La clé ouvre une session mais ne peut pas y déposer de fichier."
  warn "Le déploiement échouerait à sa première étape."
  if [ -s "$ERREUR_SSH" ]; then
    warn "Ce que ssh a répondu :"
    while IFS= read -r ligne; do warn "  $ligne"; done < "$ERREUR_SSH"
  fi
  warn "Selon le message ci-dessus, regarder les droits de"
  warn "$DOSSIER_DISTANT pour deploy, ou les restrictions de la ligne"
  warn "authorized_keys de la clé."
  rm -f "$ERREUR_SSH"
  exit 1
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Poser les secrets GitHub"
say "Cinq secrets, que « deployer.yml » lit à chaque exécution."
set_secret VPS_HOTE "$VPS_HOTE"
set_secret VPS_UTILISATEUR "deploy"
set_secret VPS_DOMAINE "$VPS_DOMAINE"
set_secret VPS_CLE_SSH "$(cat "$CLE_TEMP")"
set_secret VPS_EMPREINTE "$EMPREINTE"
say ""

# **La clé n'est effacée que si les cinq secrets sont bien posés, et cette
# condition n'est pas une précaution de principe.** `set_secret` se contente
# d'avertir quand `gh` échoue ; effacer inconditionnellement la clé privée
# juste après laisserait alors un compte `deploy` dont la moitié publique est
# installée sur le VPS et dont la moitié privée n'existe plus **nulle part**.
# Rien ne la retrouverait, et il faudrait tout reprendre.
if (( ${#SKIPPED[@]} )); then
  # **Le nettoyage automatique est désarmé ici, et c'est tout l'objet de la
  # branche.** Le `trap` posé à l'étape 5 efface le dossier de la clé à la
  # sortie ; le laisser agir dans ce cas précis détruirait la clé privée que
  # ce message annonce comme conservée, et tiendrait le pire des deux
  # mondes — l'opérateur croirait la retrouver là où plus rien ne serait.
  # L'empreinte, elle, reste nettoyée : elle se relève à la relance.
  trap 'rm -f "$HOTES_CONNUS"' EXIT
  warn "Des secrets n'ont pas été posés. La clé privée est CONSERVÉE ici :"
  note "  $CLE_TEMP"
  note ""
  note "Posez le secret manquant vous-même, puis effacez-la :"
  note "  gh secret set VPS_CLE_SSH < $CLE_TEMP"
  note "  rm -rf $CLE_DOSSIER"
else
  # La clé vit désormais dans les secrets GitHub, et sa moitié publique sur
  # le VPS. La garder ici en ferait un troisième exemplaire, sur la machine
  # la moins protégée des trois. Le `trap` s'en chargerait à la sortie ; le
  # faire ici permet de l'annoncer, et de ne pas laisser la clé traverser
  # l'affichage du verdict.
  rm -rf "$CLE_DOSSIER"
  say "  [ok] clé privée effacée de cette machine"
fi

_clear
# **Le verdict distingue « posé » de « prêt », et l'écart est ce qui évite de
# brûler le premier numéro de version.** Sans `.env` sur le serveur, un
# `poser-version` irait au bout de la partie coûteuse — commit sur `main`,
# tag, vérifications rejouées, deux images publiées — avant d'échouer au
# `up` sur le garde `POSTGRES_PASSWORD:?`. Le tag existant, et le workflow
# refusant de le reposer, il faudrait passer à `0.1.1` pour un fichier
# oublié.
if [[ "${ENV_MANQUANT:-0}" == "1" ]]; then
  printf '\n%s%s  ⚠ Accès posé — mais le déploiement n%sest PAS prêt%s\n\n' \
    "$BOLD" "$YELLOW" "'" "$RESET"
  say "L'utilisateur, la clé et les secrets sont en place."
  printf '\n'
  warn "Il manque /opt/homecomparator/.env sur le serveur."
  note "Sans lui, la pile refuse de démarrer et le déploiement échoue après"
  note "avoir commité, tagué et publié les images — le numéro est alors perdu,"
  note "le workflow refusant de reposer un tag existant."
  printf '\n'
  say "À faire maintenant, sur le VPS :"
  note "  scp .env.prod.example $ADMIN_UTILISATEUR@$VPS_HOTE:/opt/homecomparator/.env"
  note "  ssh $ADMIN_UTILISATEUR@$VPS_HOTE"
  note "  # puis renseigner les valeurs, et générer sur place :"
  note "  #   openssl rand -base64 24   # POSTGRES_PASSWORD"
  note "  #   openssl rand -base64 24   # APP_KEY"
  note "  chown deploy:deploy /opt/homecomparator/.env && chmod 600 \$_"
  printf '\n'
  note "Voir docs/deploiement.md, section « Ce qui va où »."
  printf '\n'
  say "Ensuite seulement, déployer :"
  note "  gh workflow run poser-version.yml -f version=0.1.0"
  printf '\n'
else
  printf '\n%s%s  ✓ Déploiement prêt%s\n\n' "$BOLD" "$GREEN" "$RESET"
  say "Le workflow peut désormais se connecter au VPS, et le .env est en place."
  printf '\n'
  say "Pour déployer, depuis l'onglet Actions :"
  note "  « Poser une version » → Run workflow → 0.1.0"
  printf '\n'
  say "Ou en ligne de commande :"
  note "  gh workflow run poser-version.yml -f version=0.1.0"
  printf '\n'
fi
