#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Publication manuelle des images du carnet sur GHCR (#69, ADR-0017).
#
# Ce wizard tourne sur une MACHINE DE DÉVELOPPEMENT, jamais sur le VPS : la
# construction d'un bundle Angular sur une machine à un cœur sans swap expose
# à l'arrêt du processus par l'OOM killer, sur le serveur qui sert le carnet
# au même moment.
#
# Il n'écrit aucun secret nulle part. Le jeton GitHub ne sert qu'à ouvrir la
# session vers le registre, et la session est refermée à la fin — un secret
# qui n'existe pas ne peut ni fuir, ni expirer (ADR-0017).
#
# C'est le geste que #70 automatisera. Il se fait une fois, à la main, parce
# que #69 a besoin d'images pour être vérifiable et que #70 est bloqué par
# #69 : il faut casser le cercle quelque part.

TOTAL_STAGES=5

# Rien à persister : ce wizard ne produit pas de configuration.
ENV_FILE="/dev/null"

banner "Publier les images du carnet sur GHCR"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Vérifier qu'on est au bon endroit"
say "Ce wizard construit les images depuis le dépôt courant."
if [[ ! -f apps/api/Dockerfile || ! -f apps/web/Dockerfile ]]; then
  warn "Les Dockerfile du carnet sont introuvables depuis ici."
  note "Lancez ce script depuis la racine du dépôt :"
  note "  bash scripts/publier-images.sh"
  exit 1
fi
say "Dépôt trouvé."
note "Branche : $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
  warn "L'arbre de travail n'est pas propre."
  note "Les images porteront donc du code qui n'est pas celui d'un commit,"
  note "et la version qu'elles annonceront ne désignera rien de reproductible."
  confirm "Continuer quand même ?" || exit 1
fi
pause "Prêt à continuer ?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Le compte et la version"
say "Les images s'appelleront ghcr.io/<compte>/homecomparator-{api,web}:<version>."
step "Le compte est votre nom d'utilisateur GitHub, en minuscules :"
note "le registre refuse les majuscules dans un nom d'image."
ask GHCR_COMPTE "Compte GitHub (ex. puzzlemind004) :"
GHCR_COMPTE=$(printf '%s' "$GHCR_COMPTE" | tr '[:upper:]' '[:lower:]')
say ""
step "La version est le tag des images. Pour la première publication : 0.1.0"
note "C'est ce numéro que la route de santé rendra (#67) : il est figé dans"
note "l'image à la construction et ne peut plus être changé au démarrage."
ask VERSION "Version à publier (ex. 0.1.0) :"
if [[ -z "$GHCR_COMPTE" || -z "$VERSION" ]]; then
  warn "Compte et version sont tous deux obligatoires."
  exit 1
fi
say ""
say "On publiera donc :"
note "  ghcr.io/$GHCR_COMPTE/homecomparator-api:$VERSION"
note "  ghcr.io/$GHCR_COMPTE/homecomparator-web:$VERSION"
confirm "C'est bien cela ?" || exit 1

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Ouvrir la session vers le registre"
say "Il faut un jeton GitHub (classic) portant les droits write:packages."
open_url "https://github.com/settings/tokens/new?scopes=write:packages,read:packages&description=Publication%20manuelle%20des%20images%20HomeComparator"
step "La page s'ouvre avec les droits déjà cochés : write:packages et read:packages."
step "Donnez-lui une expiration courte — ce jeton ne sert qu'aujourd'hui."
step "Cliquez « Generate token » en bas, puis copiez-le."
warn "Le jeton ne sera PAS écrit sur le disque : il ne vit que le temps de ce script."
note "Dans Git Bash, on colle avec un CLIC DROIT (ou Shift+Inser), pas Ctrl+V."
ask_secret GH_JETON "Collez le jeton (l'affichage reste vide) :"
# Retour chariot et espaces parasites : un jeton copié depuis un navigateur
# sous Windows en traîne souvent un, invisible, et le registre rend alors un
# « denied » qui accuse le jeton plutôt que le collage. Mesuré : un \r ajoute
# un caractère à la saisie.
GH_JETON=$(printf '%s' "$GH_JETON" | tr -d '\r\n[:space:]')
if [[ -z "$GH_JETON" ]]; then
  warn "Aucun jeton reçu : le collage n'a pas abouti."
  note "Git Bash ne colle pas avec Ctrl+V — utilisez le clic droit."
  exit 1
fi
say "Jeton reçu : ${#GH_JETON} caractères."
note "Un jeton classic en fait typiquement 40 (ghp_…), un fine-grained bien plus."
if printf '%s' "$GH_JETON" | docker login ghcr.io -u "$GHCR_COMPTE" --password-stdin 2>/tmp/login-err >/dev/null; then
  say "Session ouverte vers ghcr.io."
else
  warn "La connexion au registre a échoué. Erreur exacte :"
  sed 's/^/      /' /tmp/login-err
  note ""
  note "Pistes, par ordre de probabilité :"
  note "  - le jeton doit être un « classic », pas un « fine-grained »"
  note "  - il lui faut le droit write:packages"
  note "  - le compte saisi doit être celui du jeton (ici : $GHCR_COMPTE)"
  rm -f /tmp/login-err
  exit 1
fi
rm -f /tmp/login-err
pause "Continuer vers la construction ?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Construire et pousser les deux images"
say "La construction prend plusieurs minutes. Rien à faire, sinon attendre."
say ""
step "Image de l'API…"
note "--build-arg VERSION fige le numéro dans l'image : sans lui elle dirait « dev »."
if ! docker build -t "ghcr.io/$GHCR_COMPTE/homecomparator-api:$VERSION" \
     --target production --build-arg "VERSION=$VERSION" ./apps/api; then
  warn "La construction de l'image de l'API a échoué."
  docker logout ghcr.io >/dev/null 2>&1 || true
  exit 1
fi
say ""
step "Image du front…"
note "Pas de VERSION ici : seul le Dockerfile de l'API porte cet argument."
if ! docker build -t "ghcr.io/$GHCR_COMPTE/homecomparator-web:$VERSION" \
     --target production ./apps/web; then
  warn "La construction de l'image du front a échoué."
  docker logout ghcr.io >/dev/null 2>&1 || true
  exit 1
fi
say ""
step "Envoi vers le registre…"
if ! docker push "ghcr.io/$GHCR_COMPTE/homecomparator-api:$VERSION" \
  || ! docker push "ghcr.io/$GHCR_COMPTE/homecomparator-web:$VERSION"; then
  warn "L'envoi a échoué."
  docker logout ghcr.io >/dev/null 2>&1 || true
  exit 1
fi
docker logout ghcr.io >/dev/null 2>&1 || true
say ""
say "Images publiées, et session vers le registre refermée."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vérifier la visibilité des paquets"
warn "Les deux paquets doivent être PRIVÉS."
say "Une image publique rend le code compilé lisible par qui connaît l'URL,"
say "et ne se dépublie pas utilement : elle est déjà tirée et en cache ailleurs."
open_url "https://github.com/$GHCR_COMPTE?tab=packages"
step "Ouvrez homecomparator-api, puis « Package settings »."
step "Tout en bas, « Danger Zone » : la visibilité doit être Private."
step "Faites de même pour homecomparator-web."
say ""
note "Un paquet fraîchement créé est privé par défaut quand le dépôt l'est,"
note "mais cela se vérifie plutôt que se suppose."
pause "Les deux paquets sont bien privés ?"

_clear
printf '\n%s%s  ✓ Images publiées%s\n\n' "$BOLD" "$GREEN" "$RESET"
note "  ghcr.io/$GHCR_COMPTE/homecomparator-api:$VERSION"
note "  ghcr.io/$GHCR_COMPTE/homecomparator-web:$VERSION"
printf '\n'
say "Notez ces deux valeurs, le wizard de bascule les redemandera :"
printf '    %sGHCR_COMPTE%s = %s\n' "$BOLD" "$RESET" "$GHCR_COMPTE"
printf '    %sVERSION%s     = %s\n' "$BOLD" "$RESET" "$VERSION"
printf '\n'
say "Étape suivante — copier la pile sur le VPS, puis basculer :"
note "  scp docker-compose.prod.yml Caddyfile scripts/basculer-vps.sh \\"
note "      root@srv571823:/root/"
note "  ssh root@srv571823"
note "  bash /root/basculer-vps.sh"
printf '\n'
note "Le jeton GitHub créé plus haut ne sert plus : vous pouvez le révoquer."
printf '\n'
